// packages/blog-starter-kit/themes/newsletter/components/hero.tsx
import React from 'react'
import { useAppContext } from './contexts/appContext'

const Hero = () => {
    const {publication} = useAppContext()
    const {author} = publication
  return (
    <div className='min-h-[40vh] fade-in w-[90%] pt-10 mx-auto flex flex-col items-center justify-center gap-4'>
        <h1 className='text-5xl md:text-7xl text-center uppercase dark:text-white font-[600] flex flex-col gap-0'>{author.name} <span> newsletter</span></h1>
        <p className='text-xl text-center text-gray-700 dark:text-gray-400'>{publication.descriptionSEO ? publication.descriptionSEO : "Welcome to My Blog Space: Dive into a world of thoughts and ideas."}</p>
        
    </div>
  )
}

export default Hero

// packages/blog-starter-kit/themes/newsletter/src/lib/components/Hero.svelte
<script lang="ts">
	export let name: string = 'Technalitic';
	export let description: string =
		'Random thoughts about software engineering, programming, and the future of technology.';
</script>

<div class="flex flex-col justify-around h-[70vh] max-w-5xl items-center text-white m-auto pb-40">
	<h2 class="text-3xl lg:text-7xl uppercase">{name}</h2>
	<p class="text-2xl sm:text-4xl text-center">
		{description}
	</p>

	<slot />
</div>
